//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightDetail
    {
        public int Id { get; set; }
        public string FlightName { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string ArrivalTime { get; set; }
        public string Departure { get; set; }
        public string FlightClass { get; set; }
        public Nullable<decimal> FlightCharges { get; set; }
        public Nullable<int> Seats { get; set; }
    }
}
